################################################################################
# Brew Bundle                                                                  #
# https://github.com/Homebrew/homebrew-bundle                                  #
################################################################################

################################################################################
# Taps (directories of formulae, casks, fonts, ...)                            #
# `brew tap <tap_name>`                                                        #
################################################################################
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

################################################################################
# Formulae (cli apps)                                                          #
# `brew install <formula_name>`                                                #
################################################################################

# GNU utilities (macOS uses BSD utilities by default)
# beware replacing them with GNU utilities may break stuff
# brew "coreutils"               # GNU core utilities

# GNU utilities but better (rust/go) and other utilities
brew "atuin"                   # (history)
brew "bat"                     # (cat)
brew "ccat"                    # (cat)
brew "bottom"                  # (gtop, htop, ...)
brew "broot"                   # (tree, ...)
brew "dust"                    # (du)
brew "exa"                     # (ls)
brew "fd"                      # (find)
brew "fzf"                     # (find)
brew "peco"                    # (find, ...)
brew "procs"                   # (ps)
brew "ripgrep"                 # (grep)
brew "rm-improved"             # (rm)
brew "sd"                      # (sed)
brew "zoxide"                  # (cd)

# Shells
brew "fish"                    # User-friendly command-line shell.
brew "fisher"                  # Plugin manager for fish, inspired by antigen.
brew "zsh"                     # UNIX shell.
brew "antigen"                 # Plugin manager for zsh, inspired by oh-my-zsh and vundle.
brew "starship"                # Cross-Shell Prompt.

# CLI tools
brew "asciinema"               # Record and share terminal sessions.
brew "thefuck"                 # Programmatically correct mistyped console commands.
brew "tldr"                    # Simplified and community-driven man pages.
brew "tree"                    # Display directories as trees (with optional color/HTML output).
brew "vim"                     # Improved Vi.
brew "neovim"                  # Improved Vim.
brew "tmux"                    # Terminal multiplexer.

# CLI fun
brew "cowsay"                  # Configurable talking characters in ASCII art.
brew "fortune"                 # Infamous electronic fortune-cookie generator.
brew "neofetch"                # Fast, highly customisable system info script.
brew "archey"                  # Graphical system information display for macOS.

################################################################################
# Casks (gui apps)                                                             #
# `brew install --cask`                                                        #
# Note: some apps might not have checksum => install will fail                 #
################################################################################
# Browsers
cask "brave-browser"
cask "chromium"
cask "google-chrome"

# Utilities
cask "adobe-acrobat-reader"    # PDF reader
# cask "audacity"              # Audio editor/recorder
cask "daisydisk"               # Disk space visualizer
cask "grammarly-desktop"       # Grammar checker
cask "hammerspoon"             # macOS automation tool (bridge between the OS a Lua scripting engine)
cask "keycastr"                # Open-source keystroke visualizer
cask "logitech-options"        # Logitech mouse/keyboard configuration (office series)
cask "logitech-g-hub"          # Logitech mouse/keyboard configuration (gaming series)
cask "obs"                     # Screen recorder
# cask "maccy"                 # Clipboard manager
cask "screenflick"             # Screen recorder with audio
cask "vlc"                     # Media player

# Communication/Social/Entertainment
cask "discord"
cask "microsoft-teams" 
cask "skype"
cask "steam"
cask "zoom"

# Programming
cask "anaconda"                # Python distribution + package manager
cask "docker"                  # Containerization
# cask "gitkraken"             # Git GUI
cask "hyper"                   # Cross platform terminal emulator
cask "iterm2"                  # macOS terminal emulator
cask "jetbrains-toolbox"       # JetBrains IDEs manager
# cask "miniforge"             # Community version of Miniconda (Minimal Anaconda distribution)
cask "ngrok"                   # Reverse proxy?, Expose localhost to the internet?
cask "postman"                 # API testing
# cask "sourcetree"            # Git GUI
cask "visual-studio-code"      # Text editor

# Quick Look plugins
cask "qlcolorcode"           # Preview source code files with syntax highlighting
cask "qlstephen"             # Preview plain text files without or with unknown file extension (README, CHANGELOG, package.json)
# cask "qlmarkdown"          # Preview Markdown files
# cask "quicklook-json"      # Preview JSON files

# University/Research/LaTeX
# cask "mactex"              # macOS LaTeX distribution
cask "notion"                # Note taking app
cask "obsidian"              # Markdown note taking app
cask "zotero"                # Reference manager

################################################################################
# Fonts (are actually casks)                                                   #
# `brew install --cask <cask_name>`                                            #
################################################################################
cask "font-fontawesome"
cask "font-open-sans"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-meslo-for-powerline"
cask "font-powerline-symbols"
cask "font-roboto-mono"
cask "font-roboto-mono-for-powerline"
cask "font-roboto-mono-nerd-font"

################################################################################
# Mac App Store                                                                #
# `mas install <app_name>`                                                     #
# Note: you must be signed into the AppStore                                   #
################################################################################

# Utilities
mas "Commander One",        id: 1035236694
mas "LastPass",             id: 926036361
mas "Magnet",               id: 441258766
mas "Surfshark",            id: 1437809329
mas "Toggl Track",          id: 957734279

# Productivity (office tools)
mas "Microsoft Excel",      id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word",       id: 462054704
mas "Trello",               id: 1278508951

# Communication/Social
mas "Messenger",            id: 1480068668
mas "Slack",                id: 803453959
mas "WhatsApp",             id: 1147396723

# Other 
mas "iMovie",               id: 408981434
mas "Xcode",                id: 497799835

# TODO:
# mas "istat-menus"           id: 1319778037
# ...